name: CI
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          version: 12
      - name: install dependencies
        run: yarn
      - name: test
        run: yarn test
      - name: build macos
        env:
          OS: ${{ matrix.os }}
        run: yarn electron-pack -m
        if: matrix.os == 'macos-latest'
