name: CI
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-lates, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          version: 12
      - name: install dependencies
        run: yarn
      - name: build macos
        env:
          OS: ${{ matrix.os }}
        run: yarn electron-pack
        if: matrix.os == "$OS"
