name: CI
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          version: 12
      - name: echo matrix
        run: echo "${{ matrix.os }}"
      - name: install dependencies
        run: yarn
      - name: build macos
        run: yarn electron-pack
